---
name: Test PowerShell
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4

      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          Get-ChildItem -LiteralPath ${{ github.workspace }} -Include '*.tests.ps1' | 
            ForEach-Object -Process [
              Invoke-Pester -Path $_.FullName -Verbose -Passthru
            }